### ISSUE TITLE
Paste from context menu does not update model

### ISSUE THREAD

**Issue by jjoedouglas** [angular-ui/ui-tinymce#102]
When pasting from the context menu the updateView function does not called.

This is fixed by adding a listener for the PostProcessPaste event which is made available by the paste plugin.  So the paste plugin needs to be injected during setup as well (if it's not already present).

I'd send a pull request but I'm a giant github noob and have no idea how to send two independent pull requests to the same repo. :)

**Comment by wesleycho** [comment]
I think this is now addressed with current `master`. Let me know if this is still an issue.
