### ISSUE TITLE
detect color changes

### ISSUE THREAD

**Issue by mabi** [angular-ui/ui-tinymce#103]
Color changes are not detected (and saved) I made a new commit in PR #100 addressing that, the event is fired many times, but I coud not find another one able to detect those changes.

**Comment by RopoMen** [comment]
Hi,
Could you also check that is my jsfiddle which is listening 'change' event doing the right thing to your issue as well, I commented this ticket https://github.com/angular-ui/ui-tinymce/pull/110 there is link to the jsfiddle which has 'change' event listerner added.

If that 'change' event is enough then 'nodeChange' listerner would not be needed.

**Comment by RopoMen** [comment]
Hi,
But if the 'change' event does the same thing then only that should be added, so that directive only listens relevant events and not all..

http://jsfiddle.net/RopoMen/swvcbfhm/

That jsfiddle contains 'change' event listner, but I just wanted to be sure that my 'change' event listener does what OP wanted :)

**Comment by wesleycho** [comment]
I do not think the library should bind to that event if it indeed does fire that often - that could be potentially problematic when you have a fast typer.

Because of potential performance & UX concerns, I believe this should be implemented at the user level.

**Comment by rbecheras** [comment]
@sevenbytes +1 for your solution
@wesleycho this solution is required to properly handle changes as text-colors, highlight colors, table cells and border propeties and font size. Without this fix some are not handled at all (font color for exemple) and others seems randomly handled (cell border properties for example)
