### ISSUE TITLE
The editor doesn't play nice with mceRemoveEditor and mceAddEditor commands

### ISSUE THREAD

**Issue by coud** [angular-ui/ui-tinymce#104]
If you do this. You will get an error:

Error: this.getDoc(...) is null.

While I'm debugging the issue. I found out that this is because after the editor has been removed, the tinyInstance variable in ngModel.$render still holds the old destroyed instance of the editor.

To fix this we need to listen to the 'remove' event in the setup function of the options variable and empty the tinyInstance variable.

ed.on('remove', function(e) {
     tinyInstance = null;
});

Please take a look at this and someone make a PR for this. This is important when making a popup for the editor or move the editor's parent dom on the page.

**Comment by giannisp** [comment]
Had the same issue on a legacy project.
The scenario was Fancybox + TinyMCE 4 + ui-tinymce, which required the two calls mceRemoveEditor/mceAddEditor to play nice.
The remove event you have mentioned saved the day, thanks a lot!
