### ISSUE TITLE
Use another language

### ISSUE THREAD

**Issue by Louhike** [angular-ui/ui-tinymce#105]
Hi,

I would like to use another language with the component. TinyMCE has some packages for the languages which can be added manually.

Wouldn't it be a good solution to add this packages through bower for ui-tinymce?

Or do you consider it a non-issue and that it should be managed manually.

I think it might simpler if it only needed for the user to add a new package in the Bower configuration file. If there is already a way to do it, please correct me.

**Comment by wesleycho** [comment]
I think this should be optional as currently is, as localization is dependent on each user's needs and shouldn't be marked as a hard dependency.
