### ISSUE TITLE
setContent of an textarea with tinyMCE

### ISSUE THREAD

**Issue by blabno** [angular-ui/ui-tinymce#113]
I have a wizzard that on each step renders tinymce bound to different scope variable.
When I do full page refresh the value is rendered inside tinymce, but if I'm switching between wizzard steps (ng-if) the editor does not render content.

I found solution here: http://stackoverflow.com/a/11781367

**Comment by wesleycho** [comment]
I am confused - what does setting the html content do that is special?

**Comment by wesleycho** [comment]
I believe this may be fixed now in `master` - let me know if this is not the case.
