### ISSUE TITLE
Project Unmaintained?

### ISSUE THREAD

**Issue by NgYueHong** [angular-ui/ui-tinymce#116]
The project shows build error and last commit was over 8 months ago. Really hope to see at least proper build of the project.

**Comment by LeleDev** [comment]
+1

**Comment by abhinavguptas** [comment]
Angular 1.3 and Tinymce are not going very well with each other. Its no more working with multiple Tinymce instances on same page.

I might try to fix the plugin, but no maintainer of this project is a worry :(

**Comment by naitsirch** [comment]
This is a pity :-( any volunteers who'd like to continue this project?

**Comment by svemir** [comment]
We have forked it and merged some of the outstanding pull requests. You could either do it yourself too, or let us know which ones you would like to see merged. We are currently not in a need of multiple instances on the same page, but we do plan to merge some more bug fixes. Our fork is at https://github.com/Symplicity/ui-tinymce

**Comment by wesleycho** [comment]
Most of the pre-existing issues should be fixed now in `master` (I have done some work at the request of @rbecheras).

If there are any more concerns, I would like the discussion to continue in #138, which is a call to action.
