### ISSUE TITLE
TinyMCE with Bootstrap modal

### ISSUE THREAD

**Issue by RopoMen** [angular-ui/ui-tinymce#117]
Hi,
I didn't invent this fix by myself, but I report this issue over here, because I think that this could be fixed inside this directive.

Issue is that when you initialize tinymce editor inside Bootstrap modal window and you open tinymce link editor, you cannot add link because you cannot get focus on that link dialog.

Here is discussion of that issue as well coulple of jsfiddle links where the issue is shown and fixed.

http://stackoverflow.com/questions/18111582/tinymce-4-links-plugin-modal-in-not-editable
Here is the fix from stackoverflow
```javascript
$(document).on('focusin', function(e) {
    if ($(e.target).closest(".mce-window").length || $(e.target).closest(".moxman-window").length) {
        e.stopImmediatePropagation();
    }
});
```

I know that this is a framework specific issue, but I think that if there would be generic solution which doesn't break anything else, that would be best. But there could also be some property like 'data-is-bootstrap' added to directive which could be used to add that fix....

**Comment by wesleycho** [comment]
This has a problem - if a user has multiple tinymce windows, then it may not target the desired window.

I also recommend investigating using a library like [UI Bootstrap](http://angular-ui.github.io/bootstrap/) or [Angular Strap](http://mgcrea.github.io/angular-strap/) over vanilla Bootstrap JS.

**Comment by deeg** [comment]
Closing this issue due to age. If you are still having trouble please open a new issue with a fiddle attached.
