### ISSUE TITLE
tinymce fails to render the tinymce model in the textarea after changing the order of the list that tinymce is in

### ISSUE THREAD

**Issue by leonzinger** [angular-ui/ui-tinymce#12]
I have a list of items, one of the items can be a tinymce editor. this list can change the order of the items in it. once i change the order of the items, my tinymce stops working.

here is a demo of my code(haml):

%li{:"ng-repeat"=>"item in items | toArray | orderBy:'position'",:class=>"item",:"ng-class"=>"{in_edit:item.in_edit}"}
    .edit{:"ng-show"=>"item.in_edit"}
      .close_item{:"ng-click"=>"remove(item)"}
      .save_item{:"ng-click"=>"save(item)"}
      .include{:"ng-include"=>"",:src=>"item.type"}

%script{:type=>"text/ng-template", :id=>"text"}
  %textarea{:"ui-tinymce"=>"",:"ng-model"=>"item.body"}

![image](https://f.cloud.github.com/assets/853625/659096/ba8d58c2-d65a-11e2-9012-f080211560fc.png)

![image](https://f.cloud.github.com/assets/853625/659098/cd74879e-d65a-11e2-807e-4f95d727a447.png)

**Comment by wesleycho** [comment]
Just noting here, I have a simpler plunker that reproduces the issue [here](http://plnkr.co/edit/vikkdAkGld5180jLkk2E?p=preview).

I believe I am close to a fix that creates support for a new $scope event to programmatically trigger refreshing of the directive, and hope to have one pushed up today.

**Comment by atodicebear** [comment]
Is this Solved?
Im still facing this Problem

> Just nothing here, I have a simpler plunker that reproduces the issue [here](http://plnkr.co/edit/vikkdAkGld5180jLkk2E?p=preview).

Its still the same as mentioned from @wesleycho 
I have a Table with Editors with Pagination.
Sorting this Table works fine as long there are more than >1 Pages.
As soon through Search,Filter, Deleting and so on only 1 Page lasts the Sort destroys the Editors.
As before mentioned still holding the Content but Whiteblocking the Editor -> No Edits and Functions Possible.

Is there a workaround for that at the Moment?

**Comment by prasadchaugule** [comment]
@atodicebear You saved my day. Worked like charm. Thanks!
