### ISSUE TITLE
Doesn't remove instance of Editor

### ISSUE THREAD

**Issue by zishanj** [angular-ui/ui-tinymce#120]
I am using this tinymce editor directive inside ng-repeat. When I try to remove specific instance from the list then it always trigger the $destroy on last element in the list. For example, if I have a list of 4 elements and uses ng-repeat to display a list with editor and remove button; then when I click the remove button on element 2, it will trigger $destroy on last element 4 and removes that editor.

**Comment by wesleycho** [comment]
If the editor all has the same `id` attribute value in the ng-repeat, then it may not garbage collect properly - what happens if you do something like `id="foo-{{$index}}"` in the ng-repeat?

**Comment by wesleycho** [comment]
I believe this should be fixed in `master`. Be sure to remove the `id` attribute if you are using it, as I made an update to the API of the directive in order to correctly manage situations with `ng-repeat` and `ng-if`.
