### ISSUE TITLE
How to get Plain Text

### ISSUE THREAD

**Issue by ammar91** [angular-ui/ui-tinymce#128]
Is there anyway, I can get extract plain text from actual model value? The model binding works great, I am just wondering if somehow I can get plain text (unformatted version) as well? 

Any help on this would be appreciated.

**Comment by alexbowers** [comment]
I have worked this out, and sent in a pull request. for now it is here:

https://github.com/angular-ui/ui-tinymce/pull/130

**Comment by wesleycho** [comment]
This feature is now available in `master`. Try out the `format` key, with value as supported by TinyMCE as documented [here](http://www.tinymce.com/wiki.php/api4:method.tinymce.Editor.getContent). You can use the value of `'raw'` (default value) or `'text'`
