### ISSUE TITLE
uiTinymce should remove tinymce instance on $scope destruction FAILED

### ISSUE THREAD

**Issue by rbecheras** [angular-ui/ui-tinymce#134]
Running unit test on the last commit  cause fails

	$ grunt
	Running "jshint:files" (jshint) task
	>> 3 files lint free.

	Running "karma:unit" (karma) task
	INFO [karma]: Karma v0.12.35 server started at http://localhost:9876/
	INFO [launcher]: Starting browser Chrome
	WARN [web-server]: 404: /favicon.ico
	INFO [Chromium 41.0.2272 (Ubuntu 0.0.0)]: Connected on socket Y6kehwI0-Kr-tvtQIFXW with id 24219114
	Chromium 41.0.2272 (Ubuntu 0.0.0): Executed 2 of 7 SUCCESS (0 secs / 0.067 secs)
	Chromium 41.0.2272 (Ubuntu 0.0.0): Executed 3 of 7 SUCCESS (0 secs / 0.176 secs)
	Chromium 41.0.2272 (Ubuntu 0.0.0) uiTinymce should remove tinymce instance on $scope destruction FAILED
	        Expected null to be undefined.
	        Error: Expected null to be undefined.
	            at /home/remi/_projects/ui-tinymce/test/tinymce.spec.js:69:34
	Chromium 41.0.2272 (Ubuntu 0.0.0): Executed 4 of 7 (1 FAILED) (0 secs / 0.2 secs)
	Chromium 41.0.2272 (Ubuntu 0.0.0): Executed 7 of 7 (1 FAILED) (0.295 secs / 0.291 secs)
	Warning: Task "karma:unit" failed. Use --force to continue.

	Aborted due to warnings.

Thus all builds failsl on travis.

**Comment by wesleycho** [comment]
Fixed via 2b3554da0e9d67393130b7f9d62f3531d94ec473
