### ISSUE TITLE
Need quality maintainer for project

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/ui-tinymce#138]
For some reason, I have become the maintainer of this repository, even though I did not create this project, nor am heavily involved.

For the near term, I do happen to have time to contribute some for this library, but I would like to find a/some true long term maintainer(s) who can take control of this and upgrade this project as necessary. Any interested people should have high code quality and understand the challenges of maintaining an open source project (or learning to do so).

**Comment by rbecheras** [comment]
Hi @wesleycho, I am candidate for that. I never maintained an active open source project but I want to learn and I want to evolve in open source community. I am passionate and I understand and love the free software challenges. Maintaining this repository could be a nice start to me and I'd be happy to do it.

**Comment by deeg** [comment]
Closing as duplicate #176. I plan to start helping out as much as I can, but will keep other issue open for now.
