### ISSUE TITLE
Adding iframe via source results in <img> 

### ISSUE THREAD

**Issue by ddalcu** [angular-ui/ui-tinymce#140]
It seems the output of TinyMCE to angularjs view module is the WYSYWYG html instead of the source html.

When embedding a iframe, the output results in a <img src="placeholder"> instead of the actual iframe.

**Comment by ddalcu** [comment]
Fixed it on my side by not setting the format:raw option.
var content = editor.getContent({format: options.format}).trim(); //options.format is hardcoded to 'raw'
to
var content = editor.getContent();

**Comment by phuyem** [comment]
Thanks ddalcu for the WORK-AROUND. I am gonna open an issue

**Comment by deeg** [comment]
Closing this as a duplicate of #163. Will take care of it there.
