### ISSUE TITLE
0.0.8 tag created too early?

### ISSUE THREAD

**Issue by svemir** [angular-ui/ui-tinymce#142]
It seems that tag 0.0.8 was created without updating bower.json and package.json version numbers. I would have created a pull request to fix it, but I don't think thats possible once that tag is "out"

Perhaps version needs to be updated to 0.0.9 and new tag created after that, but maybe there is a better way.

**Comment by wesleycho** [comment]
Hmm, thanks for catching this. I will release 0.0.9 shortly then with that fixed.

**Comment by wesleycho** [comment]
Should be released now.
