### ISSUE TITLE
Adding a "setup" to the options breaks everything

### ISSUE THREAD

**Issue by Boux** [angular-ui/ui-tinymce#143]
When you do
```
// extend options with initial uiTinymceConfig and
// options from directive attribute value
angular.extend(options, uiTinymceConfig, expression);
```
You actually replace the options.setup that you define a few lines above that extend. This breaks all the ngModel functionality and a bunch of other things.

I've added a quick fix by doing this when you create the expression object to extract the custom setup function so that it doesn't replace the default one in the default object.
```
angular.extend(expression, scope.$eval(attrs.uiTinymce));
var customSetup = expression.setup;
delete expression.setup;
```

And then I simply change the few lines where it's called by this.
```
if (customSetup) {
  customSetup(ed, {
    updateView: updateView
  });
}
```
And now it works. It's an ugly quickfix though, as it doesn't really take into consideration a setup function that would be in the uiTinymceConfig object.

**Comment by ameoba32** [comment]
I faced the same issue, I need setup method to add custom button, like below. But it does not work because original "setup" method is overriden.
$scope.tinymceOptions = {
        theme: "modern",
        skin: "light",
        resize: false,
        setup: function(ed) {
            ed.addButton('mybutton', {
                title : 'My button',
                image : 'quill.png',
                onclick : function() {
                    $scope.openDialog();
                }
            });
        }
    };


My fix is change
 options = {
to 
 var setupOptions = {

and add
options = {}
angular.extend(options, uiTinymceConfig, expression, setupOptions);
instead of 
angular.extend(options, uiTinymceConfig, expression);

**Comment by tym-network** [comment]
@ameoba32 fix is working. It should definitely be integrated in the code.

**Comment by adrianthedev** [comment]
+1

**Comment by kulinsj** [comment]
+1

**Comment by deeg** [comment]
+1

**Comment by deeg** [comment]
Going to look into both this and pull request #166. Will use which ever option looks and works better. Please feel free to comment if you like one approach over the other. This issue will be solved one way or another with the next release.

**Comment by deeg** [comment]
This is in the latest v0.0.10 release.

**Comment by adrianthedev** [comment]
Thanks!
