### ISSUE TITLE
How to get the instance and invoke execCommand() method?

### ISSUE THREAD

**Issue by Jeff-Tian** [angular-ui/ui-tinymce#147]
I want to insert some extra content to the tinymce, and if I use pure tinymce I can achieve that by 

    tinymce.activeEditor.execCommand('mceInsertContent', false, 'your content');

How do I achieve it with `ui-tinymce`?

**Comment by deeg** [comment]
You can add a setup function to the options object. The function gets passed the editor as the first argument.

```
$scope.tinymceOptions = {
    setup: function(editor) {
        //Save editor to var or execCommand here.
    }
}
```

Please note that there are a few issues (#143, #166) where adding a setup function may break some other things. I plan to have this fixed on the next release coming out soon.
