### ISSUE TITLE
data-mce-bogus="1" appears on model

### ISSUE THREAD

**Issue by orzilca** [angular-ui/ui-tinymce#150]
Hi,

I think there is a bug in the latest version.

I implement ui-tinymce and the editor works great, except that tinymce's default element appears on the modal if no value was inserted to the editor.

```javascript
$rootScope.tinymceConfig  = {
        inline: false,
        resize: false,
        valid_elements : "a[href|target=_blank],strong/b,div[align|dir],br,ul,ol,li,hr,p[dir],span[dir]",
        toolbar: "bold italic underline | link image | bullist numlist | alignleft aligncenter alignright | ltr rtl | removeformat code",
        plugins: "autolink link image directionality paste code",
        paste_as_text: true,
        paste_auto_cleanup_on_paste: true,
        paste_remove_spans: true,
        paste_remove_styles: true,
        paste_retain_style_properties: false,
        skin: 'lightgray',
        menubar: false
      };
```
```html
<textarea rows="10" class="form-control"
                                  ui-tinymce="tinymceConfig"
                                  ng-model="someModal"></textarea
```

The model value (when the editor is empty) is set to be:
```html
<p><br data-mce-bogus="1"></p>
```

If I understand correctly, this code block is a root element pushed by tinymce in case that the editor is empty in-order to enable mouse clicks on the editor.. it shouldn't appear in the model.

**Comment by longzheng** [comment]
I've also encountered this issue. Upon some investigation, this appears to be because this directive defaults the tinyMCE ```format: 'raw'``` which spits out unfiltered HTML when the model is updated. https://github.com/angular-ui/ui-tinymce/blob/master/src/tinymce.js#L102

The code that updates the model uses the ```format```
```
            var content = editor.getContent({format: options.format}).trim();
```

A better default would be ```format: 'html'``` which spits out an empty string if the editor is empty.

**Comment by orzilca** [comment]
It seems to be working, thanks @longzheng !

**Comment by deeg** [comment]
Thanks for reporting. I believe I have seen this to, but I want to get in a habit of requiring a Plunker or Fiddle on issues.

I will look into this issue as well, and hope to have it fixed by the next release if still a problem.

**Comment by deeg** [comment]
I decided to default to html format, and allow the user to override with format set on options passed to ui-tinymce.

Thanks for taking the time to help out!

**Comment by wangchuanyin** [comment]
editor.getContent({format: ''}) seems like ok also
