### ISSUE TITLE
not working for ng-minLength and ng-required

### ISSUE THREAD

**Issue by phuyem** [angular-ui/ui-tinymce#151]
Hello,
Adding ng-minLength and ng-required (not tested with other angular validation) will break ng-model

Thanks

**Comment by deeg** [comment]
Please update the issue with a Plunker or Fiddle re-creating.

**Comment by deeg** [comment]
Closing this ticket as a duplicate of #145. I will add min-length to that ticket.

Ng-required alone should be fixed now. Thanks for reporting.
