### ISSUE TITLE
tinyMCE.get('id') is not working

### ISSUE THREAD

**Issue by eloone** [angular-ui/ui-tinymce#155]
Given:

`<textarea id="myText" ui-tinymce></textarea>`

`tinyMCE.get('myText')` doesn' work.

I have to do `tinyMCE.get('ui-tinymce-0')` to make it work, but if I have several instances in a page, I can't guess this internal id. Is it possible to make `tinyMCE.get('myText')`  work?

**Comment by Mavlarn** [comment]
There is some info about this in README.md :
> Be sure not to set an id attribute. This is because the directive needs to maintain selector knowledge in order to handle buggy behavior in TinyMCE when DOM manipulation is involved, such as in a reordering of HTML through ng-repeat or DOM destruction/recreation through ng-if.

I think you should use class to get one if you have several instances.

**Comment by deeg** [comment]
What @Mavlarn says is correct. Right now you should not include an ID when using ui-tinymce directive.

You can however set a class like he suggests and get to it that way. If you feel you really need to be able to set your own ID, please open a new issue and I can set it as an enhancement and see if there is a need from the community.
