### ISSUE TITLE
Update bower to current version

### ISSUE THREAD

**Issue by sebastianjonasson** [angular-ui/ui-tinymce#159]
The current package on bower it not up to date. Could you please push the most recent release to bower.

**Comment by deeg** [comment]
This is a duplicate and not true. The latest released version is out on bower.

I would like to see a new release including some of the open pull requests though.

Would suggest closing this ticket.

**Comment by deeg** [comment]
Will be making a new release soon and make sure it gets to bower. Closing ticket.
