### ISSUE TITLE
ng-required is not working

### ISSUE THREAD

**Issue by phuyem** [angular-ui/ui-tinymce#161]
... it just not working...

**Comment by kawazoe** [comment]
My guess is this is probably caused by tinymce always returning some data in the model. It will always contain at least an empty p element.

**Comment by deeg** [comment]
Possible related to #150

**Comment by deeg** [comment]
[Here is a plunker](http://plnkr.co/edit/KwGsyE?p=preview) demonstrating ng-required working with the latest release (v.0.0.10).

If you are still having issues please ask any questions you may have using the [angular-ui-tinymce tag on StackOverflow](http://stackoverflow.com/questions/tagged/angular-ui-tinymce).

If you have any bugs please create a Plunker reproducing and open a new issue.
