### ISSUE TITLE
embedded (youtube) video not showing

### ISSUE THREAD

**Issue by phuyem** [angular-ui/ui-tinymce#163]
What you see: embed a video, it is not showing before and after submitting. Note:select-copy-past the whole video still working though.

What you get (behind) : img tag for both after embed-window and after submit form

What happened : tinymce replace iframe tag by img tag on their editor, if you inspect the value of the textareathe, you also see img tag, not iframe  . Upon form submit, they replace img tag back to iframe tag. Which mean iframe tag is being sent. 

With ui-tinymce, the value of textarea, which contain img tag, not iframe tag, is bound to your model, and sent to backend. I am not sure it is a bug but it need to be changed or documented

Work-around: Thanks to https://github.com/angular-ui/ui-tinymce/issues/140 : 
1) in your controller
 $scope.tinymceOptions = {...
format:'text'
..
}

2) in ui-tinymce / tinymce.js , line 26 (as of v0.0.9) :
Replace  
var content = editor.getContent({format: options.format}).trim();
by
            var content = editor.getContent();

Hope I will save someone time in the future

**Comment by agez** [comment]
+1 I had the same issue and "fixed" it with the workaround. @phuyem  Thanks for the hint!

**Comment by deeg** [comment]
I will look into re-creating this issue and getting the fix into the next release.

I'm not sure we want to ignore the format option when getting content, but I will take a closer look tomorrow.

**Comment by deeg** [comment]
I could not reproduce the issue, but I just made a change where it now defaults to format "html" and allows the user to override it in the options object.

This issue will get closed when the fix gets pushed to master. If you are still having issues once the fix is applied, please open a new issue with a Plunker or Fiddle demonstrating the problem you are having.
