### ISSUE TITLE
version 0.0.10 not registered with bower

### ISSUE THREAD

**Issue by jstuparitz** [angular-ui/ui-tinymce#164]
Can you please register it?

**Comment by sunil534** [comment]
Any update on this???? can you please register it ????

**Comment by d00n** [comment]
bump

**Comment by d00n** [comment]
Forked and registered: https://github.com/d00n/ui-tinymce

**Comment by breity** [comment]
+1!!

**Comment by deeg** [comment]
There is no 0.0.10 version yet.

+1 to accept some of the open pull requests and create a new non-forked version 0.0.10

**Comment by deeg** [comment]
Closing this issue. Going to get some of the open pull requests merged and release a new version 10 soon.
