### ISSUE TITLE
link inserting creates data-mce-href="..."

### ISSUE THREAD

**Issue by WayneUong** [angular-ui/ui-tinymce#165]
When I insert a url using the link plugin, the scope result has a data-mce-href="..." attribute in it even though it's not there when I view the source code with the tinymce source code viewer. It is messing up a regex for me. Is there a way to not include data-mce-href, or am I missing a clean-up step somewhere?

scope variable:

```
<a href="http://www.gamespot.com/" data-mce-href="http://www.gamespot.com/">http://www.gamespot.com/</a>
```

view source code using tinymce:

```
<a href="http://www.gamespot.com/">http://www.gamespot.com/</a>
```

**Comment by WayneUong** [comment]
I read on the official forum that data-mce-href should be only temporary

**Comment by deeg** [comment]
@WayneUong, can you please pose a link to the form post you read if you still have it handy.

I will see if I can re-create this issue, and try to decide if it is something we need to fix on our end.

**Comment by deeg** [comment]
So I confirmed even the latest version of ui-tinymce will add ``` data-mce=href="http://www.gamespot.com/"``` to the raw content of the editor.

In the latest version of ui-tinymce we change the default format to spit out their scrubbed 'html'. See the [README.md](../blob/master/README.md) for more information.

You on your model you should get the normal a tag as you would expect.

Try loading a link into [this example](http://plnkr.co/edit/hspJb5?p=preview) and you should see it is all set.

If you are having any other issues please ask any questions using the [angular-ui-tinymce tag on StackOverflow](http://stackoverflow.com/questions/tagged/angular-ui-tinymce).

If you have any bugs please create a Plunker reproducing and open a new issue.
