### ISSUE TITLE
Update TinyMCE to current version

### ISSUE THREAD

**Issue by alex-lancer** [angular-ui/ui-tinymce#172]
Hi! Now the current version of TinyMCE is 4.2.x but just installed ui-tinymce uses v. 4.1 How can I specify to use 4.2 version?

**Comment by deeg** [comment]
+1 for bower dependency update if nothing is broken.

@alex-lancer, you should be able to get the newer version separate and link the newer version instead.

**Comment by deeg** [comment]
This is in the latest v0.0.10 release.
