### ISSUE TITLE
minified plugins

### ISSUE THREAD

**Issue by ddNils** [angular-ui/ui-tinymce#173]
in my downloaded tinymce the plugins are minified (the script files are now pluginname.min.js).

now ui-tinymce cannot load plugins :(

could you by chance provide a flag in config? Or change the lazy loading function to search for .min as well?

**Comment by deeg** [comment]
Not sure this library is the one dealing with which plugins to use.

If loading unminified TinyMCE, by default it will look for uniminified plugins. Simmilarly if loading minified TinyMCE it will look for minified plugins.

According to their documentation, to load plugins of a different type, or a different location, link them directly after the tinymce file.

http://www.tinymce.com/wiki.php/Tutorials:Creating_a_plugin

>You can also have the plugin in any location you want by loading the plugin.js/plugin.min.js files directrly after the tinymce.js/tinymce.min.js.

>Example of loading the plugin from another url
>```
<script src="/tinymce/js/tinymce.min.js"></script>
<script src="/scripts/my.tinymce.plugin.js"></script>
<script>
tinymce.init({..});
</script>```

This is working for me.

**Comment by alacret** [comment]
This issue can't be closed this isn't a solution to the minified environment problem
