### ISSUE TITLE
Height 100% + autoresize causing issues

### ISSUE THREAD

**Issue by Jakobovski** [angular-ui/ui-tinymce#202]
Thanks for the great library!

I am having an issue with the following CSS.
`html { height: 100%; }`

It seems that on every digest cycle the height is increased by a few lines. This seems to happen only when the autoresize plugin is enabled.

Do you have any recommendations on how to fix this problem?

Thanks!

**Comment by deeg** [comment]
What version of the library are you using?

Would you mind posting a Plunker demonstrating the issue? I would be more than happy to investigate.

**Comment by deeg** [comment]
@Jakobovski, are you still having issues? Were you able to create a plunker reproducing the issue?

**Comment by deeg** [comment]
Please take a look at [CONTRIBUTING.md](https://github.com/angular-ui/ui-tinymce/blob/master/CONTRIBUTING.md).

If you have found a bug, please open a new issue with a plunker re-creating it.
