### ISSUE TITLE
scope of this directive should be isolated if configured

### ISSUE THREAD

**Issue by sajadghobadi** [angular-ui/ui-tinymce#216]
im am using this directive but scope of tinymce is not isolated therefore when i use multiple editor in page by same config ng-model of all editor is one object

**Comment by deeg** [comment]
I am confused at the issue, you are using the same model for two editors?

Can't you just use two different models? I didn't create the directive, but actively update and maintain it. I'm assuming the team who built it, took making it an isolate scope into consideration. I will reach out to them to see if I can find out the history of why it wasn't made that way.

With that being said, if you feel that would make it better feel free to put out a PR with a plunker demonstrating the fix and why it is better and we can take it into consideration.

**Comment by deeg** [comment]
Going to close this issue as I have not heard back. Feel free to respond back here and I can re-open if needed.
