### ISSUE TITLE
reinit tinymce options cause of $scope value

### ISSUE THREAD

**Issue by QuadroKnoX** [angular-ui/ui-tinymce#219]
Hey guys I have a question or better a problem with the options:
I have a textarea
`<textarea ui-tinymce="tinymceOptions" ng-model="tinymceModel"></textarea>`
which should refresh the option content_css after a click on the button with another value. I know you can't really refresh the options, just kill and reinit but when I tried `tinyMCE.remove();` it is removing my textarea totally and then when I used `$scope.tinymceOptions` I can't reinit it, or am I just too confused?

Thx for any help :)

Quick fiddle-Sample what I mean: https://jsfiddle.net/QuadroKnoX/k6tacgwn/

**Comment by deeg** [comment]
Take a look at the demo included with the project for how to use it.

I am confused with your question. Looking at the fiddle, I don't even see ui-tinymce or tinymce included anywhere, is it?

Also why are you setting $scope.CSS to be the model of the first input? What is supposed to go in there?

I am going to close this ticket as I do not see a bug, but I can continue to help here if you have more questions.

**Comment by QuadroKnoX** [comment]
Well the problem is that I want to manually change the css path and when I hit refresh, that it reloads the editor with the new path of the content_css, but when I use `tinymce.remove()`, it is removing the textarea and I dont know how to use the similar function of `tinymce.init()` in the angular version after that.

**Comment by deeg** [comment]
Can you try using the event '$tinymce:refresh'.

```$scope.$emit('$tinymce:refresh');```

This should refresh the editor and not remove it. Let me know how you make out.

**Comment by QuadroKnoX** [comment]
Unfortunately nothing is happening. I've tried `$scope.$broadcast('$tinymce:refresh');` too but this one is just adding another instance of the editor and the old one doesnt get updated.

**Comment by deeg** [comment]
Ah yes, my fault, glad it is working for you now.
