### ISSUE TITLE
Updated npm package?

### ISSUE THREAD

**Issue by philcraven** [angular-ui/ui-tinymce#220]
We are in the process of moving away from bower and it would be great if the npm package for this project was at the latest release.

**Comment by deeg** [comment]
Thanks for posting. I will get to this tomorrow.

**Comment by deeg** [comment]
Sorry need to look into who owns the npm package module.

Just to be certain, which npm package are you using, incase multiple are registered?

**Comment by deeg** [comment]
I am reaching out to the owner of [angular-ui-tinymce package](https://www.npmjs.com/package/angular-ui-tinymce) to get publishing rights. If it does not work out, I will create a new NPM package under a different name. Sorry again for the delay.

**Comment by breity** [comment]
+1 @deeg Thanks for looking in to this. We're using jspm, so it will be great to have the npm package up-to-date.

**Comment by deeg** [comment]
@philcraven and @breity, it looks like the current owner is going to transfer it, just waiting.

I will get it done asap. Again sorry for the delay.

**Comment by breity** [comment]
@deeg, No worries. Thanks again.

**Comment by philcraven** [comment]
Thanks for the help!

**Comment by deeg** [comment]
Sorry for the delay. Should be all set.

https://www.npmjs.com/package/angular-ui-tinymce

**Comment by breity** [comment]
Thanks!
