### ISSUE TITLE
$setUntouched

### ISSUE THREAD

**Issue by ton0913nguyen** [angular-ui/ui-tinymce#231]
ngModel.$setUntouched(); is not a function (line 66)

**Comment by deeg** [comment]
Can you please post a plunker reproducing the problem?

**Comment by deeg** [comment]
Please take a look at [CONTRIBUTING.md](https://github.com/angular-ui/ui-tinymce/blob/master/CONTRIBUTING.md).

If you have found a bug, please open a new issue with a plunker re-creating it.

**Comment by deeg** [comment]
My guess this is related to your version of angular.

The latest release of this library is tested with the latest 1.4.x version. Is it possible to update?

I am going to think about adding checks in to protect against this error or making a decision to interface with a certain version of angularjs and note the breaking change. Will get back to you soon.

**Comment by deeg** [comment]
Going to close this issue. The recommendation is to update to the latest stable angular (1.4.9).
