### ISSUE TITLE
Can't type on mobile when using inline

### ISSUE THREAD

**Issue by laurensnl** [angular-ui/ui-tinymce#237]
On mobile (iOS, Safari & Chrome), I can select a div that has ui-tinymce, but I can't type. The keyboard does show up, but typed letters don't show up in the div and are not added to the model. 

This is the div:

`<div ui-tinymce="tinymceOptions" class="form-control-tinymce" ng-model="news.newItem.text" style="min-height: 4em;"></div>`

These are the options:

`$scope.tinymceOptions = {
	inline: true,
	plugins : 'autolink, autoresize, charmap, image, imagetools, link, paste, table',
	browser_spellcheck : true,
	autoresize_min_height: 450,
	autoresize_max_height: 500,
	autoresize_bottom_margin: '50',
	menubar: 'edit insert format table tools',
	default_link_target: '_blank'
};`

The css class only has some borders and height.

I'm using:
- tinymce#4.3.3 (also tried 4.3.7)
- angular-ui-tinymce#0.0.14

Typing does work when I change the div into a textarea, but then the textarea is filled with this text:

`&lt;br data-mce-bogus="1"&gt;`

Happens on desktop & mobile. When I change it, it changes back to that string.

**Comment by deeg** [comment]
Can you please set up a plunker with your exact example and I can take a look into fixing it?

**Comment by laurensnl** [comment]
Thank you for your quick reply Dan! I'm leaving for holiday now but I'll make a Plunker as soon as I'm back.

**Comment by laurensnl** [comment]
Tried it in a Plunker and it worked, so I guess there's something else in my app that breaks it. I'll dive into it!

**Comment by deeg** [comment]
Great, feel free to open a new issue or report back here if you find it is a bug.
