### ISSUE TITLE
Form gets $dirty after touching the model.

### ISSUE THREAD

**Issue by MrMartiniMo** [angular-ui/ui-tinymce#238]
Still running into the form gets $dirty issue (#48, #107).

http://plnkr.co/edit/INfZpLpz2yrRvlHitw1N?p=preview

**Comment by deeg** [comment]
The plunker does not seem to load angular-ui-tinymce correctly.

Do you mind fixing it up and I can take a look?

**Comment by MrMartiniMo** [comment]
plunker updated. thanks @deeg

**Comment by deeg** [comment]
Thanks for updating, it indeed still seems like a bug.

I will take a look into fixing it. PRs are welcome if you already started looking at it.

**Comment by MrMartiniMo** [comment]
It is somewhere in [`updateView`](https://github.com/angular-ui/ui-tinymce/blob/master/src/tinymce.js#L26).

```JavaScript
console.log('dirty', form.$dirty)
ngModel.$setViewValue(content);
console.log('dirty', form.$dirty)
```

Maybe we need to check if the content has changed or not.

**Comment by raphael-m** [comment]
It seems that the issue still exists when `debounce` is set to false.
