### ISSUE TITLE
Copy and paste on Firefox doesn't update the model

### ISSUE THREAD

**Issue by pelizza** [angular-ui/ui-tinymce#240]
When doing a copy and paste action using Firefox, it seems TinyMCE doesn't fire "change" event and so the model is not updated.

Trying to troubleshoot the problem I've found [this link](http://archive.tinymce.com/wiki.php/API3:event.tinymce.Editor.onPaste). It seems there is a special event for paste events, fired on all browsers.

Maybe listening to "paste" event to update the model is enough to resolve this issue. Did someone else notice that?

**Comment by asulaiman** [comment]
+1 seeing the same behavior on Chrome.

**Comment by MrMartiniMo** [comment]
I think it is a bug in tinymce itself. My current workaround is adding the `paste`-Plugin.

https://plnkr.co/edit/2Q1KfaUdh77XutpuhzsP?p=preview

**Comment by shyamal890** [comment]
@asulaiman @MrMartiniMo I don't think this is the case anymore. Try this [plunker](https://plnkr.co/edit/6UhXkA4AzEFNjl1DvyQU?p=preview). 

Just remove the `ng-model-options` from the html and copy-paste. As soon as you press a space or the editor losses focus the model is updated.

**Comment by pelizza** [comment]
Yeah, at a first sight, I can't reproduce it anymore. Although, it still doesn't update the model as soon as you paste the content, differently from when something is typed.

I'll try harder to reproduce the issue here.

**Comment by pelizza** [comment]
It really seems to be vanished. The curious thing, is that I cannot reproduce it even using the same version of both ui-tinymce directive and tinymce editor.

Maybe is something related to recent browser versions...

**Comment by pranjal-goswami** [comment]
Adding the paste plugin as suggested by @MrMartiniMo worked like a charm!
