### ISSUE TITLE
Update Angular version dependency to 1.3.x

### ISSUE THREAD

**Issue by RopoMen** [angular-ui/ui-tinymce#243]
Hi,

I have AngularJS 1.2.12 in use and I did install latest ui-tinymce and I'm getting error 
"tinymce.min.js:1 Uncaught TypeError: q.$setUntouched is not a function"

`$setUntouched` is not available in AngularJS 1.2.x series, it is [introduced](https://code.angularjs.org/1.3.0/docs/api/ng/type/form.FormController) in AngularJS 1.3.0

**Comment by RopoMen** [comment]
Option 2, this would still be compatible with other AngularJS versions.
```js
if(angular.isFunction(ngModel.$setUntouched) {
ngModel.$setUntouched();
}

**Comment by deeg** [comment]
Going to require 1.4.x or greater now.
