### ISSUE TITLE
Updating dependency

### ISSUE THREAD

**Issue by VigneswaranMarimuthu** [angular-ui/ui-tinymce#246]
Hi,

Can you update angular dependency ? I am using latest angular code base and since this plugin uses 1.4, my Jenkins builds are failing.

**Comment by deeg** [comment]
@VigneswaranMarimuthu, I have not checked it with Angular 1.5 yet but I will do that and update the dependency.

**Comment by VigneswaranMarimuthu** [comment]
Thanks :)

**Comment by breity** [comment]
+1. Any chance this can be updated soon (or @madflow's pull request be accepted)? We're using Angular 1.5.x too in our project. Thanks.

**Comment by deeg** [comment]
Closed via fd0dc39576ce17030683db753491e171401a6dc2
