### ISSUE TITLE
Cannot read property 'body' of undefined exception since TinyMCE 4.3.13 - works with TinyMCE 4.3.12

### ISSUE THREAD

**Issue by Kimpossibru** [angular-ui/ui-tinymce#264]
When doing a bower update, you now get TinyMCE 4.3.13 rather than 4.3.12 (since a couple of hours). This causes the exception "Cannot read property 'body' of undefined" for me.
As a workaround, I've installed 4.3.12 via my own bower.json again. That solved the problem for now. You may want to look into why 4.3.13 doesn't work with ui-tinymce - perhaps report issues to tinyMCE directly if you find something.

**Comment by mykbaker** [comment]
I am also getting this error, had to revert back to 4.3.12.

**Comment by adrianorsouza** [comment]
Had the same issue today with tinymce `v4.3.13` as @Kimpossibru said manually add `v4.3.12` to `bower.json` works fine.

In my case this error appears when I set the options attribute like so: `ui-tinymce="tinymceOptions"` without options set it works fine with `v4.3.13`.

**Comment by paulo17** [comment]
Got the same error on v4.3.13 but work fine in v4.3.12

**Comment by jbrizio** [comment]
Mee too! With the version 4.3.12 Work fine

**Comment by Lezeper** [comment]
Get same error on latest version.

**Comment by deeg** [comment]
Sorry for the delay, I will look at this later today and see if we can fix it.

**Comment by soniccat** [comment]
@deeg while trying to figure out the reasons of the crash I got that Editior.init call happens later than toggleDisable by timer. And after toggleDisable call in getWin I have empty self.iframeElement. And the crash happens  here because of empty body

```tinyInstance.getBody().setAttribute('contenteditable', true);```

**Comment by mja-maia** [comment]
the same error here

**Comment by jgerlach** [comment]
Any progress on this?

**Comment by guilherme6191** [comment]
+1

**Comment by comm1x** [comment]
+1, still has problem on 4.3.13

**Comment by pcunha03** [comment]
+1

**Comment by Jony-Y** [comment]
+1

**Comment by fabiogallo-blueprint** [comment]
+1
Btw, it's still a problem with tinyMCE latest release, v4.4

**Comment by Tangeek59** [comment]
Same issue for me, with latest release

**Comment by alvachien** [comment]
+1

Same issue occurs in tinymce V4.4.

**Comment by SteveyPugs** [comment]
+1

**Comment by ymind** [comment]
+1

**Comment by rash2x** [comment]
+1

**Comment by moritzpflaum** [comment]
I made a plnkr showing the issue:
http://plnkr.co/edit/R7oHmGcRkKz5ZZXSFo9h

And one showing it fixed:
http://plnkr.co/edit/F1QJlRPN8M04n3yNCgm5

The tests fail because of the line 
    ``beforeEach(module('ui.tinymce'));``

which resets the variable ``generatedIds`` to zero before every test, resulting in duplicate ids in the test DOM. If it is replaced with something global, the tests pass. This should not happen in non-test use, I think. I just don't know how to tell jasmine to load the module only once.

**Comment by thomasvnl** [comment]
@moritzpflaum Thank you, just what I needed to fix the error.

**Comment by Tangeek59** [comment]
@moritzpflaum Thanks a lot, working for me too ;)

**Comment by guilherme6191** [comment]
I didn't quite get it. I don't think it happens only in a tested suit.

What is exactly the change to fix this?

**Comment by reginaldocmrg** [comment]
In my case It was solved, in Angular2, using setTimeout.

**Comment by moritzpflaum** [comment]
@guilherme6191 
The issue happens in production.
What only happens in the environment of the unit tests is the unit tests failing, because the angular-directive definition is run multiple times and always resets the "unique" counter for the id.

This is not a problem by itself, but the unit tests continue to append directives with the same '0' value id to the **same DOM**.
This makes tinymce mess up (by destroying the tinymce instance with id '0' while another test just initalized an instance with that same id) and causes the tests to fail.

The issue mentioned in #264 is fixed by using the new tinymce-init-promise when available.
Once the tests are fixed regarding the 'unique id' issue, they will pass using the promise.

I hope this makes sense.

**Comment by thomasvnl** [comment]
For me it happened in development mode when running an angularjs app with
grunt.

Op vr 22 jul. 2016 20:04 schreef moritzpflaum <notifications@github.com>:

**Comment by KRaymundus** [comment]
I had the same problem, solved it by commenting the line 142:
`toggleDisable(scope.$eval(attrs.ngDisabled));`

**Comment by CyborgMaster** [comment]
I appears to me that @moritzpflaum, may have a fix.  Are we waiting for a PR from him?

**Comment by moritzpflaum** [comment]
@CyborgMaster I made a PR and it's passing CI.
Someone just needs to accept & merge it. There are some other issues/PRs, too.

**Comment by bobzurad** [comment]
@moritzpflaum The files in the two plnkr's you posted have the same exact code. What's the difference? 

I took @KRaymundus' advice and commented out line 142 to fix it. 

Thanks everyone!

**Comment by peterkc** [comment]
Adding a $timeout in toggleDisable() seems to fix it. I am not sure if this would cause other issues.

```
function toggleDisable(disabled) {
    $timeout(function() {
        if (disabled) {
            ensureInstance();

            if (tinyInstance) {
                tinyInstance.getBody().setAttribute('contenteditable', false);
            }
        } else {
            ensureInstance();

            if (tinyInstance && !tinyInstance.settings.readonly) {
                tinyInstance.getBody().setAttribute('contenteditable', true);
            }
        }
    }, 150);
}
```

**Comment by Rouche** [comment]
Did the solution explained here and fixed it:
https://github.com/tinymce/tinymce/issues/2722

**Comment by ohjames** [comment]
I reverted back to 4.3.12 via `bower install --save tinymce-dist#4.3.12` but after running that bower installs to a folder `tinymce` (not `tinymce-dist`) and from then on every time I run `bower install` it gets `tinymce-dist` as well, leaving me with two versions of tinymce, one with a -dist prefix at the broken version and the one I want.

**Comment by ohjames** [comment]
Ah `bower install` rewrites the `bower.json` entry according to the `name` in `bower.json` so you have to edit the file after running this and then run `bower install` again.

**Comment by zero-degrees** [comment]
Commenting out the toggleDisable line isn't a good solution. I submitted a PR for a more robust fix that waits for TinyMCE to start up.

**Comment by asaarnak** [comment]
Any progress?

**Comment by zero-degrees** [comment]
Yes. It works reliably for me, and I submitted a PR. There is a failing
test, but that appears to be a preexisting issue.
