### ISSUE TITLE
UI-tinymce editor not even showing after building the project with grunt build. Do i need to change options?

### ISSUE THREAD

**Issue by digvijayatjax** [angular-ui/ui-tinymce#265]
editor works fine in development but its not working anymore when i build it with minification of files...
guys help me out....is there anyone whos has this kind of error....do i need to change tinymce options in the controller??

**Comment by rguruprakash** [comment]
I came across similar issue, check if tinymce's theme, skin and plugin directories are getting copied to your dist folder

I dont know if its clean or not, but adding following line to my grunt-copy config solved my issue

`{cwd: 'bower_components/tinymce-dist/', src: ['plugins/**', 'themes/**', 'skins/**'], dest: 'dist/', filter: 'isFile', expand:true}`

**Comment by digvijayatjax** [comment]
not working , I added the above code in copy.js file, but its not adding those files in dist folder..

**Comment by deeg** [comment]
Can you please post a plunker reproducing your issue with the minified files, or show the error in question?

**Comment by mostafabarmshory** [comment]
h faced with the same problem.
In my case, based on the console log, I change the copy pattern as follow:


		    {
			cwd : 'bower_components/tinymce/',
			src : [ 'plugins/**', 'themes/**',
			    'skins/**' ],
			    dest : 'dist/scripts',
			    filter : 'isFile',
			    expand : true
		    }

**Comment by alairjt** [comment]
+1

**Comment by nblasgen** [comment]
@mostafabarmshory solution worked for me.  Not quite sure why it was necessary, but I don't need to know.

**Comment by deeg** [comment]
I am going to close this issue as this is not an issue with ui-tinymce library itself.

If you feel there is still an issue in this library please open an new issue with a plunker recreating the issue.
