### ISSUE TITLE
Formats (styleselect) tooltip not showing

### ISSUE THREAD

**Issue by fernandodof** [angular-ui/ui-tinymce#268]
Hello, 

I noticed that all the buttons on the editor toolbar have a tootip, exept the "Formats" button.
Has this bug already been addressed ? (is it a bug ?) 

Example: http://embed.plnkr.co/vL7MqL/ 

Thank you.

**Comment by deeg** [comment]
This is not a bug in this library. If you look at the [TinyMCE Homepage Example](https://www.tinymce.com/) you will see the same behavior there.

If you believe this is a bug with TinyMCE, I would post a bug on their [github issues page](https://github.com/tinymce/tinymce/issues).
