### ISSUE TITLE
Cannot read property 'body' of undefined ?

### ISSUE THREAD

**Issue by RobinCodeX** [angular-ui/ui-tinymce#270]
![image](https://cloud.githubusercontent.com/assets/8408783/16349972/5518528a-3a8e-11e6-8b49-23e7b59851a9.png)

```html
<script src="https://cdn.bootcss.com/angular.js/1.5.7/angular.min.js"></script>
<script src="https://cdn.bootcss.com/tinymce/4.3.13/tinymce.min.js"></script>
<script src="/angular-ui-tinymce/src/tinymce.js"></script>
<script>
var master = angular.module('master',['ui.tinymce']);
</script>
<body ng-app="master">
	<div id="container">
		<div>
			<textarea ui-tinymce ng-model="tinymceModel"></textarea>
		</div>
	</div>
</body>
```

Idk this error how to fix this error.

**Comment by andela-smartins** [comment]
Hi @RobinCodeX, how did you resolve the above error? I just got the error too when I upgraded to the latest version

**Comment by RobinCodeX** [comment]
@andela-smartins use version 4.3.12, see https://github.com/angular-ui/ui-tinymce/issues/264

**Comment by cengkuru** [comment]
Had this issue before. i solved it by commenting out toggleDisable(scope.$eval(attrs.ngDisabled)); in lie 142
