### ISSUE TITLE
Unit tests failing for versions of tinymce >= 4.3.13

### ISSUE THREAD

**Issue by lee-tunnicliffe** [angular-ui/ui-tinymce#276]
INFO [Chrome 51.0.2704 (Mac OS X 10.11.4)]: Connected on socket JdQ1Ub4KOxbanMWXi3C0 with id 20342993
Chrome 51.0.2704 (Mac OS X 10.11.4): Executed 0 of 11 SUCCESS (0 secs / 0 secs)
Chrome 51.0.2704 (Mac OS X 10.11.4): Executed 1 of 11 SUCCESS (0 secs / 0.06 secs)
Chrome 51.0.2704 (Mac OS X 10.11.4): Executed 2 of 11 SUCCESS (0 secs / 0.072 secs)
Chrome 51.0.2704 (Mac OS X 10.11.4): Executed 3 of 11 SUCCESS (0 secs / 0.077 secs)
Chrome 51.0.2704 (Mac OS X 10.11.4) uiTinymce compiling this directive should execute the passed `setup` option FAILED
	Expected spy setupFooBar to have been called.
	    at /Users/tunnicliffel/Projects/ui-tinymce/test/tinymce.spec.js:63:35
Chrome 51.0.2704 (Mac OS X 10.11.4): Executed 4 of 11 (1 FAILED) (0 secs / 0.275 secs)

It appears that the provided setup function is no longer being called.

**Comment by deeg** [comment]
@lee-tunnicliffe, I saw you opened a PR and then closed it. Was it not fixed with your changes?

Do you want to re-open it? I think there is an issue with the latest version of TinyMCE, I still need to look into. I hope to make some time to do that today.

**Comment by deeg** [comment]
I am going to close this for now. The tests are a mess, and I haven't had time to get to them yet.

I have commented out all broken tests, and the rest should be working at current time. If anyone wants to take a stab at cleaning up the tests, please feel free to open a PR.
