### ISSUE TITLE
tinymce dependencies

### ISSUE THREAD

**Issue by jeanmatthieud** [angular-ui/ui-tinymce#284]
The "tinymce-dist" bower package is the same as the "tinymce" package.
As the package name in the "bower.js" file is "tinymce", the dependency of "angular-ui-tinymce" should be "tinymce" instead of "tinymce-dist".

The current dependency is not compatible with builders like "brunch".

**Comment by rbecheras** [comment]
I agree, I was going to post the same issue before found yours.
