### ISSUE TITLE
Combine plugins into one single HTTP request

### ISSUE THREAD

**Issue by mcblum** [angular-ui/ui-tinymce#288]
I don't know if this is a ui-tinymce issue or what but each instance of TinyMce is loading like 10 plugins and if there are a bunch of editors on one page it turns into many, many requests and takes quite a while. Any idea if there's a way to fix this and serve just one JS file?

**Comment by deeg** [comment]
This is more of a support request for TinyMCE. Ui-tinymce does not change how TinyMCE loads its plugins.

I would suggest checking out [their plugins docs](https://www.tinymce.com/docs/plugins/) or posting a question on [TinyMCE's StackOverflow](http://stackoverflow.com/questions/tagged/tinymce)

**Comment by bmurphy-affirma-zz** [comment]
@mcblum Did you ever find a solution to this?  Trying to work around this same issue.

**Comment by mcblum** [comment]
@bmurphy-affirma I did not. I ended up moving on to Angular 5 and using Froala Editor and so far I'm happy with it.
