### ISSUE TITLE
TinyMCE not all textareas when using ng-repeat.

### ISSUE THREAD

**Issue by theonemule** [angular-ui/ui-tinymce#289]
I've run into an issue with TinyMCE on using it in an ng-repeat. 

When my application starts, it loads some data from a service. The ng-repeat is bound to an array from the service. When it runs, some of the textareas aren't rendered while others are. There does not seem to be a pattern, as I can't consistently make it do the same behavior on the same textareas every time the app runs.  Notice the last two textareas in the screenshot....

![image](https://cloud.githubusercontent.com/assets/7351945/18761307/607eeadc-80d2-11e6-8ae9-53ab11a1191e.png)

However if I add items to an array one at a time using something like a button, it works without a problem.

**Comment by deeg** [comment]
Going to close this issue as it is a support question. Feel free to continue discussion and we can help if there is enough information and time.

A plunker with a live demonstration of the issue would be helpful.

**Comment by rsmith-sonovate** [comment]
I think this may be a bug. I had a very similar issue using the latest version (0.0.17), I solved it be reverting to 0.0.15

**Comment by sreekamalesh123** [comment]
I am using tinyMCE 4.7.5. I am unable to resolve this issue. Can anyone suggest me some solution?
