### ISSUE TITLE
Allow custom skins

### ISSUE THREAD

**Issue by aoakeson** [angular-ui/ui-tinymce#296]
When creating a custom skin, and referencing it with the skin attribute, I am getting 404s because it thinks it is trying to load it from cloud front, when it is actually loading from the disk. It does load correctly, and place the right skin on, I just receive these errors in the console. 

It is trying to load these files, which error out in the console:
https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.4.3/skins/material-admin/skin.min.css 
https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.4.3/skins/material-admin/content.min.css 

Here is my configuration code:
```
$scope.tinymceOptions = {
     inline: false,
     plugins: 'advlist autolink code link image lists charmap preview autoresize spellchecker table',
     toolbar: 'code | fontsizeselect | fontselect',
     skin: 'material-admin',
     theme: 'modern'
    };
```

**Comment by deeg** [comment]
Going to close this as it is a support question.

I believe you should be able to use skin_url property. I don't think this would be an issue with angular-ui tinymce, but rather tinymce itself.
