### ISSUE TITLE
Tinymce in ionic modal

### ISSUE THREAD

**Issue by jieves** [angular-ui/ui-tinymce#299]
Hi

Has anyone tried to integrate the tinymce editor in an Ionic Modal window ? 
In my case it just does not render. When I put it on the main page, it al works fine.

Anyone has a solution for this problem ?

Regards
  Joost

**Comment by rbecheras** [comment]
You should start by opening a question on stackoverflow:

> http://stackoverflow.com/questions/ask

tagging `tinymce, ui-tinymce, ionic, javascript, html5` for example, and posting your code, with the versions you use for each component (`ionic`, `tinymce`, `ui-tinymce`).

Maybe there is a bug, but before, we should investigate on your implementation.

@deeg I suggest you close this issue for now.
@jieves You even can post here the link of your stackoverflow question.

Personally, I'll take a look to.
