### ISSUE TITLE
New release (0.0.17) does not worked stability with tinymce

### ISSUE THREAD

**Issue by EnvySky** [angular-ui/ui-tinymce#303]
I have two tinymce editors in one page. After upgrade, the first editor always displays the toolbar but the second sometime works, sometime not.

Could you take a look this issue for me?

I has reverted to version 0.0.16 with tinymce 4.3.12 and them always work normally.

**Comment by rbecheras** [comment]
Your issue is probably related to #295, #304 and #302. 
I think you should take a look to these issues/PR, it could help you investigate your issue.

**Comment by deeg** [comment]
Fixed in 0.0.18 release.
