### ISSUE TITLE
refresh content_style without full tinymce:refresh?

### ISSUE THREAD

**Issue by piercy** [angular-ui/ui-tinymce#306]
Hey,
Not an issue as such, but some help i require.  I'm creating a drag and drop html editor using your angular directive for tinymce.  I have a scenario where  i need to apply and change the content_style dynamically.  The reason for this is the user can setup different heading styles and we would like these to be reflected in the editor.

I can make it work by setting the required CSS in the content_style property and then forcing a refresh by doing:
`$rootScope.$broadcast('$tinymce:refresh');`

However, this seems to have quite a drastic performance impact.     I'm looking to try find a way to refresh the CSS but without forcing the whole editor to refresh.  Is this possible at all? 

Any thoughts or ideas are greatly appreciated.  

Many Thanks,
Michael

**Comment by piercy** [comment]
you know what, im an idiot.  Change it to $scope not $rootScope and it works much better now.  Turns out just writing down your problem can fix it .. who knew!

**Comment by rbecheras** [comment]
Hi @piercy,

you're right it's not an issue.

In the future, in you search any help, please post a question on stackoverflow instead of posting an issue here.

> http://stackoverflow.com

You could use the following tags:

- `angularjs`
- `tinymce`
- `angular-ui`
- `angular-ui-tinymce`
