### ISSUE TITLE
Cannot type small letter 'y'

### ISSUE THREAD

**Issue by moumoune** [angular-ui/ui-tinymce#309]
Thank for this project. Unfortunately we found an issue which is impacting high to our customers. The issue is, when we manually typing letter 'y' from keyboard, its not getting displayed on the editor (version"latest" of angular-ui-tynimce) but working for capital letter 'Y'.

**Comment by luispeerez** [comment]
Same here, using 0.0.17 version

**Comment by atodicebear** [comment]
Check this out maybe it helps you
https://github.com/tinymce/tinymce/issues/3363

**Comment by moumoune** [comment]
Hi, thank you for the answer, but I had already watched this issue.

The problem is not in the TinyMCE library but in ui-tynimce, because their dependency on TinyMCE is not up to date with the fix !

**Comment by moumoune** [comment]
In their bower.json :

```json
"dependencies": {
    "angular": ">=1.4.0",
    "tinymce": "~4.5.0"
  }
```
The 4.5.0 version cause the 'y' error, not the 4.4.3...

**Comment by moumoune** [comment]
It's works fine now. :+1:
