### ISSUE TITLE
Simple TinyMce Errors "o is not Constructor" and "property onload of null"

### ISSUE THREAD

**Issue by atodicebear** [angular-ui/ui-tinymce#316]
As in the Title Mentioned a simple setting up of TinyMce throws this 2 Errors.
In Detail
`TypeError: o is not a constructor` is thrown when I open the Site with the Editor.
`TypeError: Cannot set property 'onload' of null` is thrown when I change from the Site with the Editor to any other Site.
More Details at
http://stackoverflow.com/questions/41617815/simple-tinymce-throws-o-is-not-constructor-and-property-onload-of-null
Could be a Bug?

**Comment by deeg** [comment]
Please do not use this for support questions, but only for bugs which can be reproduced by a plunker.

**Comment by eudago** [comment]
this is a bug, reopen plz

**Comment by ashieshkumar90** [comment]
put jquery.min.js file under header Section of the page above any script. this trick worked for me.
