### ISSUE TITLE
iOS - clicking outside tinymce editor doesn't close keyboard

### ISSUE THREAD

**Issue by RustyDev** [angular-ui/ui-tinymce#317]
We're running into issues with the iOS keyboard not closing when clicking outside the tinymce instance. Not sure if this is a ui-tinymce or tinymce issue.

I've set up a simple CodePen that has a normal textarea and a tinymce instance. Typing in the textarea and then clicking submit properly closes the iOS keyboard. The same isn't true for the tinymce instance.

http://codepen.io/rustydev/full/eb9013ae528b9cbd700fb2e15d144bbf/

**Comment by deeg** [comment]
@RustyDev, it should be pretty easy to see if it is a tinymce or ui-tinymce issue.

I do not have an iphone, but can you try brining up [TinyMCE's Demo](https://www.tinymce.com/docs/demo/basic-example/) on the phone in question and see if the same issue exists?

**Comment by RustyDev** [comment]
It still persists so it looks like an issue with tinymce itself.
