### ISSUE TITLE
Can you implement this via import as opposed to a script tag?

### ISSUE THREAD

**Issue by MichaelFromin** [angular-ui/ui-tinymce#326]
I know that I can add ui-tinymce to a project via a script tag:

`<script type="text/javascript" src="app/bower_components/angular-ui-tinymce/src/tinymce.js"></script>`

...does this directive allow me to use ES2015 style imports instead?  Something like:

`import 'angular-ui/dist/tinymce';`

I don't see anything in the readme on this approach so just curious if its possible.

**Comment by madflow** [comment]
Hi, - short answer yes!

```import angularTinyMce from 'angular-ui-tinymce';```

Thanks for the upstream work :D
