### ISSUE TITLE
Hey I propose myself as a maintainer

### ISSUE THREAD

**Issue by dassiorleando** [angular-ui/ui-tinymce#365]
Hey @all,
Still looking for maintainers?
I love Angular and I would like to give some contributions to this project.
Cheers,

**Comment by deeg** [comment]
@dassiorleando can you please contact me at dan@gornstein.com and I will setup a time for us to talk.

Would love to let someone give this library some love again. Thanks!

**Comment by dassiorleando** [comment]
Ok ok.
