### ISSUE TITLE
TinyMCE Set Content calls are not updating NgModel

### ISSUE THREAD

**Issue by thoersch** [angular-ui/ui-tinymce#37]
The only update model bindings are for 'ExecCommand' and 'KeyUp' which takes care of the majority of update to the editor window, however, if you make a change to the source code directly via the editor 'Source Code' button, the model is *not* updated unless making an a keystroke so the 'KeyUp' binding executes. 

Quick Reproduce:
* enter text
* see model change
* edit via source code and add valid content and hit 'Ok'
* see model is not updated with the added content

I'm attaching a pull request that binds to 'SetContent' in addition to 'KeyUp' and 'ExecCommand'.

---

After submitting this, I see that this was added Aug. 4th and I had an outdated version. However, when I updated to current version, it's not working for me still (my example from source code). 

It appears to break when I open the editor again (I have the editor inside a angular ui modal). It now works as intended initially, but if I reopen the modal, the bindings seem to be messed up and I am unable to change the contents of the editor without it reverting back to its original state.

**Comment by wesleycho** [comment]
Closing as I believe this is outdated. Feel free to comment if this is not the case.
