### ISSUE TITLE
Inline editors do not work

### ISSUE THREAD

**Issue by jonrimmer** [angular-ui/ui-tinymce#41]
When TinyMCE is configured to appear in "inline" mode, via the ```inline: true``` configuration option, then text entry does not work properly. With a textarea element, the text disappears, whereas with divs, the caret is repeatedly moved to the beginning of the content, resulting a kind of backwards-writing effect. See this plunkr for a demonstration (happens in Chrome and Firefox).

http://plnkr.co/edit/w86QRKvuTAJKd9TZvR9a?p=preview

**Comment by wesleycho** [comment]
This should be fixed via cafdfa71e98be0faeaebe9a21e34f2c3ebd092ed

**Comment by SafinRR** [comment]
Hello!
I find trouble with inline again.
Error is: Uncaught Error: Syntax error, unrecognized expression:"tinymce.min.js:2 Uncaught Error: Syntax error, unrecognized expression: textarea#"

**Comment by deeg** [comment]
What version of the library are you using?

Can you please post a plunker showing your example with the issue?

**Comment by hoohaman** [comment]
Want to say that we have the same trouble only in Firefox.

**Comment by deeg** [comment]
What version of the library are you using?

Can you please post a plunker showing your example with the issue?

**Comment by aske-cph** [comment]
I have the same problem.

Angular tinymce doesn't work on textareas / text shows as raw:

on osx with:

Safari
Chrome
Firefox 

Angular Ui Tinymce - 0.0.11
Tinymce 3.1

**Comment by deeg** [comment]
Can you please post a plunker demonstrating the issue so we can look into fixing it?

**Comment by aske-cph** [comment]
Of course!

I will when i figure out how to add dozens of external files to plunker, (the newest version of tinymce).

Just spent an hour trying to get plunker to work with the correct versions. They ones present in the package search are old.

**Comment by aske-cph** [comment]
Okay figured it out.

http://plnkr.co/edit/10H6rbwP3xycbb493F9B?p=preview

Plunkr with versions:

versions:
Angular Ui Tinymce - 0.0.11
Tinymce 4.3.1

As you see, the textarea doesn't parse the text and you cant edit.

**Comment by re-gor** [comment]
I have the same problem in Chrome. I use last versions of angular-ui-tinymce and tinymce.
Noted that if I holding left mouse button on textarea I can print something. While I am printing this way error occurs in console log:

Error: [$sce:unsafe] Attempting to use an unsafe value in a safe context.
http://errors.angularjs.org/1.4.7/$sce/unsafe
    at http://localhost:3001/bower_components/angular/angular.js:68:12
    at htmlSanitizer (http://localhost:3001/bower_components/angular/angular.js:16673:13)
    at getTrusted (http://localhost:3001/bower_components/angular/angular.js:16837:16)
    at Object.sce.(anonymous function) [as getTrustedHtml] (http://localhost:3001/bower_components/angular/angular.js:17517:16)
    at Array.<anonymous> (http://localhost:3001/bower_components/angular-ui-tinymce/src/tinymce.js:121:35)
    at $$parseAndValidate (http://localhost:3001/bower_components/angular/angular.js:25256:38)
    at $commitViewValue (http://localhost:3001/bower_components/angular/angular.js:25246:10)
    at http://localhost:3001/bower_components/angular/angular.js:25389:14
    at Scope.$eval (http://localhost:3001/bower_components/angular/angular.js:15989:28)
    at Scope.$apply (http://localhost:3001/bower_components/angular/angular.js:16089:25)

**Comment by aske-cph** [comment]
Any news on the problems?

Otherwise inline seems broken in all browsers with the current versions.

**Comment by deeg** [comment]
Sorry for the delay. I am going to look into it this week. I am going to re-open the issue for now.

**Comment by deeg** [comment]
Changing the textarea to a div in your example, everything works fine.

[Their documentation states:](https://www.tinymce.com/docs/get-started/use-tinymce-inline/) 

>Most common TinyMCE integrations use the editor in its classic form-based mode. In this integration mode the editor usage is as a form field that is filled out to provide content. The editor is always visible as part of the form to be edited.

>Inline editing mode blends the editable view with the readable view of the page. Elements are replaced inline with an editor once clicked rather than the editor always being visible.

>Most significantly, when using inline editing TinyMCE is not isolated from the page by virtue of being encapsulated within an iframe. This has the advantage of ensuring that the content within the editor inherits the surrounding page's styles when presenting the content.

>Since the editor is not sandboxed in an iframe in inline editing mode, CSS styles for the editor's content will be inherited from the page that the editor is on. This allows you to edit content exactly as it appears within the context of the page, providing a true WYSIWYG editing experience.

Is there any reason you want to use a textarea instead of a div in this situation? You will see [their example](https://www.tinymce.com/docs/demo/inline/) also does not use a textarea. I think you will find this issue has more to do with the TinyMCE library itself, rather than the angular wrapper.

**Comment by iJungleboy** [comment]
I'm new to tinymce and this module but got inline to work within minutes. Textarea should never work as inline, that is "the wrong way to do things" as inline should keep the original tag (textarea) and textarea doesn't support formating. 

Here's a screenshot of successful integration in 2sxc from yesterday when I just got started 

![image](https://cloud.githubusercontent.com/assets/5321186/12137839/3afe351a-b454-11e5-954f-8d8a53299d02.png)

...so I would close this issue

**Comment by dfabreguette-ap** [comment]
Hi !
Looks like I have the exact same origin problem in inline mode.
When I type in my cursor moves to the beginning of the line. like @jonrimmer @gunnarlium.
Any idea ?

**Comment by dfabreguette-ap** [comment]
My bad, I was using on the same element "ng-bind-html".

**Comment by mtutty** [comment]
Sorry, we're still seeing it fail.  The $scope var is not updated, even though it does initially bind from the ng-model var.

Try changing the content in the first editor tab.  The p below is bound to the same scope var, and the button shows the scope var.  Neither of these shows the right value after changing the bound tinymce div.

http://codepen.io/mtutty/pen/NdMyBv

**Comment by strategeens** [comment]
We are also experiencing the same problem.

Inline editor often doesn't save added content. Sometimes it saves well. Console is empty, no errors.

On Chrome it doesn't save amost half of the times. On Firefox it doesn't save only around 10%.

**Comment by strategeeks** [comment]
We are also experiencing the same problem.

Inline editor often doesn't save added content. Sometimes it saves well. Console is empty, no errors.

On Chrome it doesn't save amost half of the times. On Firefox it doesn't save only around 10%.

**Comment by TOuhrouche** [comment]
Same issue here, the caret keeps going to the beginning of the line. Tried both Div and Text area, still the same :(

**Comment by patrickbussmann** [comment]
Same here.
Its rendered like...

     <div _ngcontent-c14="">
          <editor _ngcontent-c14="" name="Text" _nghost-c8="" ng-reflect-inline="true" ng-reflect-name="Text" class="ng-untouched ng-pristine ng-valid">
               
               <div id="tiny-react_21502752331535284906777" class="mce-content-body" contenteditable="true" style="position: relative;" spellcheck="false">
                    <p><br data-mce-bogus="1"></p>
               </div><input type="hidden" name="tiny-react_21502752331535284906777">
          </editor>
     </div>

But looks empty. 😢 

![2018-08-26 14_13_53](https://user-images.githubusercontent.com/15617021/44628114-525faf80-a93a-11e8-9868-fecf67f37335.png)
