### ISSUE TITLE
Wrong theme url

### ISSUE THREAD

**Issue by orzilca** [angular-ui/ui-tinymce#44]
Using angular-ui-tinymce & ng-boilerplate.

TinyMCE tries to load the theme file from the directive folder:
```
http://localhost/smartangular/build/vendor/angular-ui-tinymce/src/themes/modern/theme.js 
```

Trying to set any of this settings and nothing happens!
```javascript
{
base: '',
relative_urls: false,
document_base_url: 'path/to'
theme_url: 'path/to'
}
```

**Comment by fabiopaiva** [comment]
I got this error using bower install. I solved with:

    angular.module('myApp', []).config(function() {
        tinyMCE.baseURL = '/bower_components/tinymce';
        tinyMCE.suffix = '.min';
    })

**Comment by AquilaSagitta** [comment]
Simple fix is just to add theme and skin directories to you're /dist/scripts

**Comment by ssuryar** [comment]
In Gruntfile.js

```
// Copies remaining files to places other tasks can use
copy: {
            dist: {
                files: [{
                    expand: true,
                    dot: true,
                    cwd: '<%= yeoman.app %>',
                    dest: '<%= yeoman.dist %>',
                    src: [
                        '*.{ico,png,txt}',
                        '.htaccess',
                        '*.html',
                        'modules/**/*.html',
                        'images/{,*/}*.*',
                        'styles/fonts/{,*/}*.*'
                    ]
                }, {
                    expand: true,
                    cwd: '.tmp/images',
                    dest: '<%= yeoman.dist %>/images',
                    src: ['generated/*']
                }, {
                    expand: true,
                    cwd: 'bower_components/bootstrap-sass-official/assets/fonts/bootstrap/',
                    src: '*',
                    dest: '<%= yeoman.dist %>/fonts'
                }, {
                    expand: true,
                    cwd: 'bower_components/tinymce-dist/themes/modern/',
                    src: ['**'],
                    dest: '<%= yeoman.dist %>/core/themes/modern/'
                }, {       
                    expand: true,
                    cwd: 'bower_components/tinymce-dist/skins/',
                    src: ['**'],
                    dest: '<%= yeoman.dist %>/core/skins/'
                }, {
                    expand: true,
                    cwd: 'bower_components/tinymce-dist/plugins/link/',
                    src: ['**'],
                    dest: '<%= yeoman.dist %>/core/plugins/link/'
                }, {
                    expand: true,
                    cwd: 'bower_components/font-awesome/fonts/',
                    src: '*',
                    dest: '<%= yeoman.dist %>/fonts'
                }]
            },
            styles: {
                expand: true,
                cwd: '<%= yeoman.app %>/modules',
                dest: '.tmp/styles/',
                src: '{,*/}*.css'
            }
        },
```

**Comment by pilmee** [comment]
Set value:
angular.module('ui.tinymce', [])
  .value('uiTinymceConfig', {
    baseUrl: window.location.protocol + window.location.pathname + '/js/'
  })

....

**Comment by JavaTimeWilson** [comment]
Hi There getting the same issue. Really driving me round the bend :(

got an unusual setup here, from a Java background and am trying to get this up.
Followed the steps from this link:
https://www.tinymce.com/docs/integrations/angularjs/

however getting a 404 for loading 
http://tinymce.cachefly.net/4.0/themes/modern/theme.min.js 

I am unsure what this could be

I am loading 

"tinymce/themes/modern/theme.min.js"
"tinymce/tinymce.js" 
"jquery.min.js" 
"angular/angular.min.js"
"bootstrap/dist/js/bootstrap.js"
"angular-ui-tinymce/src/tinymce.js"

in that order, I have also tried pilmee's solution, does not work for me.

We are a java house and am intergrating angular and tinyMice

**Comment by JavaTimeWilson** [comment]
I know that this is a closed thread. but just wanted to share, 
The comment from 
                                ketilovre commented on 5 Jun 2014
solved it, loaded all the libs, the issue for me was placing this line in the config of the Angular module


angular.module('myApp', []).config(function() {
    tinyMCE.baseURL = '/bower_components/tinymce';
})
