### ISSUE TITLE
A delay in setting the model will cause tinymce to remain empty

### ISSUE THREAD

**Issue by honeyd** [angular-ui/ui-tinymce#49]
Here is a Plunker to demonstrate the issue: http://plnkr.co/edit/D1UFaF

I have put a timeout around setting the model that contains the content that should display in tinymce. As you can see in the Plunker, the regular 'ol textarea eventually loads up, but tinymce does not.

I'm using AngularJS 1.2.0-rc3, and the latest version of tinymce (4.0.8 at this moment).

**Comment by JohannMarx** [comment]
iWang's solution worked for me too - thanks!

**Comment by Nirajyadav1992** [comment]
dfasdfsadf
