### ISSUE TITLE
Loading data from a Service before the ngModel.$render call.

### ISSUE THREAD

**Issue by a-lucas** [angular-ui/ui-tinymce#62]
I want to load a set of predefined colors trough a service called Colors.

Modifying the 'uiTinymceConfig' after it was first declared would break the editor.

I made it work modifying the source code : 

replacing : 

    setup: function (ed) {
            var args;
            ed.on('init', function(args) {
                ngModel.$render();
            });

By 

    setup: function (ed) {
            var args;
            ed.on('init', function(args) {
                
                ed.settings.beforeRender(ed);
                ngModel.$render();
            });

Then, in my controller, I can define the options this way : 

    $scope.tinymceOptions = {
            beforeRender : function(ed){
                Colors.loadPrimaryColors().then(function(c) {
                    ed.settings.textcolor_map = c;
                });
            },
            toolbar: "hr table code forecolor backcolor bold italic underline strikethrough alignleft aligncenter alignright alignjustify styleselect  fontselect fontsizeselect cut copy paste bullist numlist outdent indent blockquote undo redo removeformat ",
            menubar: true,
            plugins: "textcolor code",
            textcolor_rows: 2,
            textcolor_cols: 5
    };

The mce is render correctly, and most importantly, the editor's model is updated when changes are done. (Which wasn't the case  initially).

I am new to github, and would love to contribute to some pieces of code. Any help would be appreciated.

**Comment by wesleycho** [comment]
How I would do this is wrap the element with the ui-tinymce attribute with a div element with `ng-if`, and only toggle the `ng-if` condition to true when the relevant data is returned and the desired configuration value is set (I recommend using the `setup` configuration option).

Closing as I believe this is already achieveable.
