### ISSUE TITLE
Angular UI Tinymce deletes content from ng-model and 2-way binding does not work when not using `<textarea>`

### ISSUE THREAD

**Issue by egervari** [angular-ui/ui-tinymce#69]
One problem I am having with TinyMCE editor and Angular UI's light wrapper is that ng-model doesn't appear to do the 2-way binding that I would expect with the model data on the scope when changes are made in the editor. This problem only seems to happen when `<div>` or `<p>` is used. 

The 2-way binding seems to work just fine when I use `<textarea>`, but this is not what I want... I want an inline editor.

Here are my options:

    $scope.tinymceOptions = {
        inline: true,
        menubar: false,
        statusbar: false,
        toolbar: "bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link | removeformat"
    };

In my case, if there is content in `pageElement.text`, it will actually get put into the TinyMCE editor just fine. **However**, once TinyMCE does this, the text is deleted from `pageElement.text` altogether, and the `ng-model` binding that it has to `pageElement.text` is no longer being respected:

    <div class="pageParagraph">
        <div class="contenteditable"
             ui-tinymce="tinymceOptions"
             ng-model="pageElement.text"></div>
        <p>{{pageElement}}</p>
    </div>

Here's a screenshot:

![Displaying inline problem][1]

  [1]: http://i.stack.imgur.com/R5nCr.png

How can I get 2-way binding to occur when TinyMCE is in inline mode?

**Comment by wesleycho** [comment]
This should now be fixed in `master`.
