### ISSUE TITLE
There seems to be no way to disable the control

### ISSUE THREAD

**Issue by Danita** [angular-ui/ui-tinymce#74]
It doesn't honour parent `<fieldset>` ng-disabled state...

```html
<fieldset ng-disabled="true">
	<textarea ui-tinymce="opts" ng-model="myModel"></textarea>
</fieldset>
```

And it even won't respect own `ng-disabled` directive.

```html
<textarea ui-tinymce="opts" ng-model="myModel" ng-disabled="true"></textarea>
```

This is important for example to prevent the user to continue writing text on the control after he has submitted the form.

**Comment by wesleycho** [comment]
7554a1d7e0cd6a3fe2024b31d6b81294e7e177b5 should implement disabling on the textarea element (or any other element with the directive on it).

I am not sure we can do anything about respecting the fieldset one since we have no knowledge of the parent element. I understand that that would have accessibility implications though.

Perhaps we can support a disabled option in the option object for disabling that is watched.

**Comment by steverob** [comment]
@wesleycho `0.0.9` does add `ng-disabled` support. But problem is initally if the `textarea` element has `ng-disabled="true"`, it does not work.

But if `ng-disabled` is set to some expression and if it changes sometime after initialization, disabling works perfectly :+1: 

Is there a way to make it disabled while initializing?

**Comment by steverob** [comment]
And there's no way to get an attr's value without using `$observe`? :( Im getting `undefined` whenever I try to access `attrs.disabled`. Any ideas?

**Comment by wesleycho** [comment]
Perhaps I may need to update the check to use a $watch for `element.prop('disabled')` - I will investigate this.

**Comment by steverob** [comment]
Thanks @wesleycho. :) :)

**Comment by wesleycho** [comment]
Just noting for posterity, I have a reproduction of the issue [here](http://plnkr.co/edit/DXbbMuemWffLFzOlDpwM?p=preview).

A fix should not take too long.

**Comment by steverob** [comment]
@wesleycho thanks a ton!

Would you mind letting us know when this will be released? Thanks!!

**Comment by longzheng** [comment]
Unfortunately this fix doesn't seem to work for me since when ```toggleDisable``` is ran in the [```$timeout```](https://github.com/angular-ui/ui-tinymce/commit/f25bf79eafd31bca6aa08dfd8fa66ebb629d5bba#diff-1f6638fba380b04c484908d398249763R97), the ```ensureInstance()``` method at that point can't actually find the instance. ```tinymce.get(attrs.id)``` returns null.

**Comment by longzheng** [comment]
If you move ```toggleDisable(scope.$eval(attrs.ngDisabled));``` to ```ngModel.$render``` however, it works consistently since at that point the instance is available.

```
        ngModel.$render = function() {
        	ensureInstance();
        	toggleDisable(scope.$eval(attrs.ngDisabled));


          var viewValue = ngModel.$viewValue ?
            $sce.getTrustedHtml(ngModel.$viewValue) : '';

          // instance.getDoc() check is a guard against null value
          // when destruction & recreation of instances happen
          if (tinyInstance &&
            tinyInstance.getDoc()
          ) {
            tinyInstance.setContent(viewValue);
            // Triggering change event due to TinyMCE not firing event &
            // becoming out of sync for change callbacks
            tinyInstance.fire('change');
          }
        };
```

**Comment by breity** [comment]
+1

@longzheng Thanks for this fix.

**Comment by phuyem** [comment]
@longzheng your fix works !! thanks :+1:

**Comment by deeg** [comment]
If you are still having issues with this please open a new issue with a plunker re-creating the problem so we can get a fix in.
