### ISSUE TITLE
Version 0.0.5: When using ngModel the editor is emptied on focus

### ISSUE THREAD

**Issue by mruoss** [angular-ui/ui-tinymce#75]
Hi there. I just upgraded to version 0.0.5 in which, compared to 0.0.4, you added a priority to the directive. Now each time I focus my editor, its content is empty. I expect the editor to be filled with the contend of the bound model.

I'm using a textarea with ngModel whereas contentBlock.content holds some text:

```html
<textarea ui-tinymce="tinyMceOptions" ng-model="contentBlock.content"></textarea>
```

I found out that everything works fine if I  **remove the priority** from the uiTinymce directive.

**Comment by wesleycho** [comment]
Looking through the history, I don't see any particular reason why the priority was there in the first place.

I will remove it shortly.
