### ISSUE TITLE
mce does not load value from model

### ISSUE THREAD

**Issue by vgotra** [angular-ui/ui-tinymce#77]
Could you please add priority with value greater then 0 to directive.

return {
            require: 'ngModel',
            priority: 1,
            link: 

Such solution should prevent replacing your ngModel.$render.

Thanks

**Comment by wesleycho** [comment]
I believe this actually caused a bug, and had reverted it to no priority.

Can you reproduce this based on `master` in a [Plunker](http://plnkr.co/)?

**Comment by wesleycho** [comment]
I believe this bug is now fixed, along with priority being removed.
