### ISSUE TITLE
handle_event_callback, e is undefined

### ISSUE THREAD

**Issue by timjong93** [angular-ui/ui-tinymce#83]
When i add handle_event_callback to the options. In the functions handling the callback (as described in the readme.md) the parameter e is undefined this makes it impossible to check which event fired. The usecase for this is that i want to save the changes made to  remote server when focus of the editor is lost.

Has anyone had issues with this?

**Comment by wesleycho** [comment]
Looking into this, I believe this is now outdated, as the project is supporting 4.x right now and `handle_event_callback` is in 3.x.
