### ISSUE TITLE
bower is confused because of tags "0.0.5" and "v0.0.5" 

### ISSUE THREAD

**Issue by zxbodya** [angular-ui/ui-tinymce#84]
The problem is because there is two similar tags: "0.0.5" and "v0.0.5",
bower with dependency:
```
"angular-ui-tinymce": "latest"
```
will not install latest version - it will install old one from tag 0.0.5

**Comment by CyborgMaster** [comment]
Any update on this?  I'm having troubles with it myself because of this.

**Comment by CyborgMaster** [comment]
It shouldn't take much effort to fix, if we simply delete the old tag, or release v0.0.6 that should solve the problem.

**Comment by wesleycho** [comment]
I have fixed this issue today, the 0.0.5 tag has been deleted.
