### ISSUE TITLE
scope.$apply moves the caret to the beginning

### ISSUE THREAD

**Issue by IuryAlves** [angular-ui/ui-tinymce#88]
Hi, i am using the ui-tinymce directive with tinymce 3.x and change the version to 4x it's not a possibility. The problem is: when the function updateView() is called the caret of the textarea moves to the beginning and i couldn't find a solution for that.

**Comment by deeg** [comment]
I'm sorry, but this directive requires TinyMCE version 4.

If you upgrade to TinyMCE version 4 and are still having issues, please re-open a new issue with a fiddle attached showing the undesired behavior.

**Comment by IuryAlves** [comment]
@deeg  Thanks for the reply.
