### ISSUE TITLE
Link plugin: change link doesn't update model

### ISSUE THREAD

**Issue by ncharlot** [angular-ui/ui-tinymce#94]
If you change a link (not set), model is not updated.

In link `plugin.js` line 47, replacing:

    // Update model on change, i.e. copy/pasted text, plugins altering content
    ed.on('SetContent', function (e) {

By:

    // Update model on change, i.e. copy/pasted text, plugins altering content
    ed.on('change', function (e) {

is working. But I mean `SetContent`has been used for a good reason. If not I will do a PR.

**Comment by danielgolub** [comment]
This is a major issue and have to be fixed in the near future!!
@ncharlot solution worked.

**Comment by wesleycho** [comment]
I believe this is now fixed, as the library now uses the `change` event to trigger model changes.
